import type { Metadata } from 'next';

import Navbar from './components/navbar';
import './globals.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			{/* <body className='min-h-screen bg-gradient-to-t from-sky-900 to-white'> */}
			<body className='min-h-screen'>
				<Navbar />

				{/* Guidelines */}
				<svg
					className='absolute -bottom-[100px] w-full h-full'
					viewBox='0 0 400 300'
				>
					{/* Red outer lines with 3D perspective */}
					<line
						x1='-100'
						y1='270'
						x2='160'
						y2='120'
						stroke='rgba(255, 0, 0, 0.3)'
						strokeWidth='5'
					/>
					<line
						x1='500'
						y1='270'
						x2='240'
						y2='120'
						stroke='rgba(255, 0, 0, 0.3)'
						strokeWidth='5'
					/>

					{/* Yellow middle lines with depth effect */}
					<line
						x1='50'
						y1='260'
						x2='180'
						y2='140'
						stroke='rgba(255, 255, 0, 0.3)'
						strokeWidth='4'
						strokeDasharray='12 6'
					/>
					<line
						x1='350'
						y1='260'
						x2='220'
						y2='140'
						stroke='rgba(255, 255, 0, 0.3)'
						strokeWidth='4'
						strokeDasharray='12 6'
					/>
				</svg>

				{children}
			</body>
		</html>
	);
}
